### ISSUE TITLE
getURLs will lock whole Queue when not assign Key

### ISSUE THREAD

**Issue by saselovejulie** [crawler-commons/url-frontier#87]
for example 
sent 5 urls to QueueA
then i use this code to getUrls, run this code 5 times you will got 5 different urls in QueueA
the sixth time will got empty result.

        Urlfrontier.GetParams request =
                Urlfrontier.GetParams.newBuilder()
                        .setMaxUrlsPerQueue(1)
                        .setMaxQueues(0)
                        .setKey("QueueA")
                        .setDelayRequestable(600)
                        .setCrawlID(crawlId)
                        .build();

but if you not particularly the key like this code 

        Urlfrontier.GetParams request =
                Urlfrontier.GetParams.newBuilder()
                        .setMaxUrlsPerQueue(1)
                        .setMaxQueues(0)
                        .setDelayRequestable(600)
                        .setCrawlID(crawlId)
                        .build();

you can only run once, because of the secondary time will return empty.

i  checked class AbstractFrontierService.java 
looks like 

            if (currentQueue.getInProcess(now) >= maxURLsPerQueue) {
                continue;
            }

this code will refuse the request
is this correct?

**Comment by jnioche** [comment]
Sorry for the late reply, just back from holidays. Thanks for reporting this. It looks like a bug.
Could you please try running it with 'read.thread.num' set to 1? Any chance you could contribute a unit test to reproduce the issue? Thanks

**Comment by jnioche** [comment]
Just had a closer look and there is indeed a discrepancy between the behaviour of when a key is specified or not. When a key is specified we currently don't check for the number of URLs in process. I will commit a fix so that they behave the same way and we do not return anything if the number of URLs requested is lower or equal to what is already being processed.
Thanks @saselovejulie, sorry it took a year to sort
